eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.2:8761/eureka/,http://127.0.0.2:8762/eureka/
zuul:
  add-host-header: false
  routes:
    support:
      path: /openapi/support/**
      serviceId: support
