server:
  port: 7080
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangyufu19/JBOSCloud/
          search-paths: jboscloud-config/src/main/resources/server-config
          username: youfu.wang@gmail.com
          password: wangyf19

